# Generated by Django 5.0.10 on 2025-01-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_first_name_alter_profile_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Profile Picture From Social App'),
        ),
    ]
