# Generated by Django 5.0.10 on 2025-01-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Social Avatar'),
        ),
    ]
