# Generated by Django 5.1 on 2025-01-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_uid',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Social UUID'),
        ),
    ]
