# Generated by Django 5.1.4 on 2025-01-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_social_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='site_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
