# Generated by Django 5.1.4 on 2025-01-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_site_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='organizations_count',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='plan',
            field=models.CharField(choices=[('F', 'Freemium'), ('S', 'Standard'), ('P', 'Pro')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='site_email',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
