# Generated by Django 5.1.4 on 2025-01-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_organizations_count_profile_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='site_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
