# Generated by Django 5.1.4 on 2025-01-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_site_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='organizations_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
