# Generated by Django 5.1.4 on 2025-01-31 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_organizations_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number_jid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
