# Generated by Django 5.1.4 on 2025-01-31 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_phone_number_jid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_number_jid',
        ),
    ]
