# Generated by Django 5.1.4 on 2025-01-31 11:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0010_profile_phone_number_jid'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('group_id', models.CharField(blank=True, max_length=300)),
                ('subject', models.CharField(max_length=255)),
                ('subject_owner', models.CharField(max_length=255)),
                ('subject_time', models.BigIntegerField(default=12298)),
                ('size', models.IntegerField(default=1)),
                ('data_created_on_whatsapp_cloud', models.DateTimeField(blank=True, null=True)),
                ('owner', models.CharField(max_length=255)),
                ('restrict', models.BooleanField(default=False)),
                ('announce', models.BooleanField(default=False)),
                ('is_community', models.BooleanField(default=False)),
                ('is_community_announce', models.BooleanField(default=False)),
                ('join_approval_mode', models.BooleanField(default=False)),
                ('member_add_mode', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('member_id', models.CharField(blank=True, max_length=100)),
                ('push_name', models.CharField(blank=True, max_length=100)),
                ('participant_id', models.CharField(max_length=255)),
                ('admin', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_whatsapp_member', to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppGroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('creation_date_str', models.CharField(blank=True, max_length=200)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp.whatsappgroup')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_sender_message', to='whatsapp.whatsappmember')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='whatsappgroup',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='whatsapp_group_participants', to='whatsapp.whatsappmember'),
        ),
        migrations.CreateModel(
            name='NotificationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp')], db_index=True, default='SMS', max_length=255)),
                ('whatsapp_groups', models.ManyToManyField(blank=True, related_name='notification_subscriptions', to='whatsapp.whatsappgroup')),
                ('whatsapp_members', models.ManyToManyField(blank=True, related_name='notification_subscriptions', to='whatsapp.whatsappmember')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppMemberMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('creation_date_str', models.CharField(blank=True, max_length=200)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_message_recipient', to='whatsapp.whatsappmember')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_message_sender', to='whatsapp.whatsappmember')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
