# Generated by Django 5.1.4 on 2025-01-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappgroup',
            name='creation_date_str',
            field=models.CharField(blank=True),
        ),
    ]
