# Generated by Django 5.1.4 on 2025-01-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_whatsappgroup_creation_date_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappgroup',
            name='group_id',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
