# Generated by Django 5.1.4 on 2025-01-31 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_alter_whatsappgroup_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappmember',
            name='admin',
            field=models.CharField(blank=True, default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='whatsappmember',
            name='push_name',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
    ]
