# Generated by Django 5.1.4 on 2025-01-31 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0005_whatsappmembermessage_is_broadcast_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappgroupmessage',
            name='is_broadcast_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsappgroupmessage',
            name='message_id_str',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
