# Generated by Django 5.1.4 on 2025-01-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0006_whatsappgroupmessage_is_broadcast_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmembermessage',
            name='remote_jid',
            field=models.CharField(default='status@broadcast', max_length=300),
        ),
    ]
