# Generated by Django 5.1.4 on 2025-01-31 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0007_whatsappmembermessage_remote_jid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappgroupmessage',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatsapp.whatsappgroup'),
        ),
    ]
