# Generated by Django 5.1.4 on 2025-01-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0008_alter_whatsappgroupmessage_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappgroupmessage',
            name='media_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappmembermessage',
            name='media_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
