# Generated by Django 5.1.4 on 2025-01-14 14:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_profile_organizations_count_profile_plan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(db_comment='Unique UUID for the organization', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='Organization Name')),
                ('hashed_name', models.CharField(blank=True, editable=False, max_length=100)),
                ('project_count', models.IntegerField(default=2, help_text='The maximum number of projects per Organization', verbose_name='Project Count')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_organizations', to='users.profile')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
    ]
