# Generated by Django 5.1.4 on 2025-01-25 12:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_organization_created_at_organization_is_active_and_more'),
        ('users', '0009_alter_profile_organizations_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(db_comment='Unique UUID for the Project', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('group_name', models.CharField(max_length=100)),
                ('group_admin', models.CharField(blank=True, max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_group_profile', to='users.profile')),
            ],
        ),
    ]
