# Generated by Django 5.1.4 on 2025-01-25 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0003_group'),
        ('users', '0009_alter_profile_organizations_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='profile',
            new_name='creator',
        ),
        migrations.RemoveField(
            model_name='group',
            name='group_admin',
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='groups', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.group', unique=True)),
            ],
        ),
    ]
