# Generated by Django 5.1.4 on 2025-01-25 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0004_rename_profile_group_creator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmembership',
            name='group',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='GroupMembership',
        ),
    ]
